let num = Number(prompt('Digite um número: '))
let titulo = document.getElementById('numero-titulo')
let texto = document.getElementById('texto')
titulo.innerHTML = num
texto.innerHTML += `<p>Raiz quadrada: ${num ** 0.5} <br> </p>`
texto.innerHTML += `<p>${num} é inteiro: ${Number.isInteger(num)} <br> </p>`
texto.innerHTML += `<p>É NaN: ${Number.isNaN(num)} <br> </p>`
texto.innerHTML += `<p>Arredondando para baixo: ${Math.floor(num)} <br> </p>`
texto.innerHTML += `<p>Arredondando para cima: ${Math.ceil(num)} <br> </p>`
texto.innerHTML += `<p>Com duas casas decimais: ${num.toFixed(2)} <br> </p>`